### ISSUE TITLE
Affordance Extract

### ISSUE THREAD

**Issue by SshiJwu** [yxKryptonite/RAM_code#1]
I would like to ask how to extract affordance from the droid dataset, is there any reference code?

**Comment by yxKryptonite** [comment]
Hi, thank you for your interest! We've been busy cleaning up the data and processing code and will release them soon. Please stay tuned for any updates on the data and code!

**Comment by SshiJwu** [comment]
Could you please send me the code in advance to my email? I might be in a hurry, thank you very much.
