### ISSUE TITLE
missing minkuresunet_kinect.tar

### ISSUE THREAD

**Issue by HanzhiC** [yxKryptonite/RAM_code#2]
Hi,
Thanks for the amazing work. I try to run the demo code and here is the error.

> FileNotFoundError: [Errno 2] No such file or directory: 'assets/ckpts/minkuresunet_kinect.tar'

seems the file above is missing for the demo, could you provide it?

**Comment by yxKryptonite** [comment]
Hi Hanzhi,

We added the checkpoints and updated the README. Please check them out and don't hesitate to reach out if you have further questions.
