### ISSUE TITLE
One shot imitation learning

### ISSUE THREAD

**Issue by hritam-98** [yxKryptonite/RAM_code#3]
How to use this code for one-shot imitation learning from human reference or cartoon reference, as shown on the website?

**Comment by yxKryptonite** [comment]
Hi, please check the data format in `run_realworld/real_data/demonstration` and annotate your data similarly. We will probably draft a tutorial on this in the future, so stay tuned!

**Comment by hritam-98** [comment]
Thank you for your response. May I ask the tentative date for the tutorial release?

**Comment by yxKryptonite** [comment]
Hi, I'm sorry that it is not on our original plan because we believe it would be easy to figure out getting your data annotated by yourself (given the 2D affordance annotation is relatively straightforward), but we'll try to get it done when time permits. Thanks for waiting!
