### ISSUE TITLE
python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas

### ISSUE THREAD

**Issue by gauraviiita** [yxKryptonite/RAM_code#5]
Hello,

I am trying to run the following command, but each time, my system stops working.

```
python setup.py install --blas_include_dirs=${CONDA_PREFIX}/include --blas=openblas
```

I tried following step to resolve but it did not work 

```
conda install openblas-devel -c anaconda -y

cp /home/dr/anaconda3/envs/ram/lib/libopenblas.so* \
   /home/dr/anaconda3/envs/ram/lib/python3.8/site-packages/torch/lib/.
```
But still getting the same issue. Please let me know how to fix it.

**Comment by yxKryptonite** [comment]
Hi, thank you for your interest in our work!

This command is for installing MinkowskiEngine. You can refer to https://github.com/NVIDIA/MinkowskiEngine for other installation methods or troubleshooting. If the problem still exists, you can try an alternative close-sourced AnyGrasp as the grasp pose generator (although it still requires MinkowskiEngine), see instructions [here](https://github.com/graspnet/anygrasp_sdk).

I hope the messages above could answer your questions. If you have further questions please feel free to let me know.

**Comment by gauraviiita** [comment]
Thank you for the reply. I will the official page of MinkowskiEngine in order to fix it.
