### ISSUE TITLE
Details about the simulation experiment

### ISSUE THREAD

**Issue by Bokai-Ji** [yxKryptonite/RAM_code#7]
Hi,

Thank you for the excellent work! RAM achieved impressive performance as reported in Table 1, and I have a few questions regarding the simulation experiment settings:

1. **Realistic Observations:** Does RAM face challenges in generalization due to the sim-to-real gap in RGB observations (e.g., variations in texture, background, etc.)?

2. **Success Verification:** How are success and failure defined and evaluated in the experiments? Are they determined through automated code similar to Where2Act, or are they manually verified?

3. **Built-in Rules for Success Evaluation:** If success is evaluated using built-in rules, could you describe these rules in detail? I am currently working on implementing a simulation environment, but I have encountered challenges since the one used in Where2Act cannot verify task-relevant success.
Specifically, success seems closely tied to the movement of specific parts of each instance, even within the same category (e.g., a table with drawers may have multiple movable parts). This requires identifying the target movable part for each task and instance and designing corresponding expected movements. Creating success verification code for each instance is quite labor-intensive, so any guidance or examples of how this was handled would be immensely helpful.

Thank you for your time and for sharing more details about your work!

**Comment by yxKryptonite** [comment]
Hi, thank you for your interest in our work!

1. Our method is training-free, depending on the strong generalizability of Vision Foundation Models (VFM). The dense features of VFMs can overcome sim2real domain gaps, enabling great zero-shot performance, as shown in our qualitative results in Fig. 5 of the paper.
2. As described in section 4.1, a manipulation success is defined by whether the DoF of interest (articulation joint or height) exceeds a threshold. We can easily get the values in sim so it's automatically determined through code by monitoring the change of the DoF of interest (e.g. in your case, the certain prismatic joint of a drawer).
3. Please see 2.

I hope the messages above could answer your questions. If you have further questions please feel free to let me know.

**Comment by Bokai-Ji** [comment]
Thank you for your quick response!

Just to clarify, are you saying that the DoF of interest is manually assigned for every single instance? That sounds like a significant amount of work! Will the simulation environment used in this study be made available for release?

**Comment by yxKryptonite** [comment]
Hi, sorry that I don't quite get your point. I think the verification for success is same for any method and I don't think it's a lot of work by just specifying a joint index, as in every method does. Otherwise, how can one know a drawer is open or not? It would be nice if you could provide more detailed examples.

**Comment by Bokai-Ji** [comment]
Thank you for your patience!
Taking the GAPartNet dataset as an example, it contains 1,166 object instances. For each instance, I would have to specify a joint index and an expected motion for each specific task (e.g., open, close, pick-up, etc.). That seems like annotating around 3~4k samples and would take days to finish all on myself. I was wondering if there are other convinient ways to build up the affordance evaluation pipeline more quickly. It seems unavoidable to do such annotations for me now. Thank you again for your useful advice and guidance!

**Comment by Bokai-Ji** [comment]
No further questions.
